# version format
version: 1.4.0.{build}

# UMBRACO_PACKAGE_PRERELEASE_SUFFIX will only be used for Release builds
# example UMBRACO_PACKAGE_PRERELEASE_SUFFIX=beta
install:
  - cmd: npm install -g grunt-cli

build_script:
- set UMBRACO_PACKAGE_PRERELEASE_SUFFIX=
- set UMBRACO_PACKAGE_MIN_VERSION=7.1.3
- cd package
- Build.bat

artifacts:
  - path: package\*.nupkg
  - path: package\*.zip

deploy:
  - provider: NuGet
    server: https://www.myget.org/F/nupickers/
    api_key:
      secure: SASQGWG/4zNns7bwSSsJ5RPvKcKfJsBeEPuw69wsVPA3PO739QmzVtc5VwQwgvbr
    artifact: /.*\.nupkg/
    on:
      branch: master